### ISSUE TITLE
Why do u use Rsocket

### ISSUE THREAD

**Issue by HelloTo4x** [mkrzywanski/rsocket-reactive-chat#65]
Hi,i am reading your code, why do you use Rsocket instead of other protocols like gRPC or socket, websocket... What is your use case which you use Rsocket, thank you so much

**Comment by mkrzywanski** [comment]
Hello. I used RSocket here because I wanted to learn how it works and also dive deeper into reactive programming. Also RSocket can use Websocket to transfer messages. I have not used gRPC so I do not know what adventages it has over RSocket.

**Comment by HelloTo4x** [comment]
tks
